openapi: 3.0.3
info:
  title: E-commerce Platform API
  description: REST API for managing products, orders and users in e-commerce platform
  version: 1.0.0
  contact:
    name: API Support
    email: support@ecommerce.com

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

tags:
  - name: Users
    description: User management operations
  - name: Products
    description: Product catalog operations
  - name: Orders
    description: Order management operations

paths:
  /users/register:
    post:
      tags:
        - Users
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: User with this email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users:
    get:
      tags:
        - Users
      summary: Get all users (ADMIN only)
      operationId: getAllUsers
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPageResponse'
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products:
    get:
      tags:
        - Products
      summary: Get all products (public)
      operationId: getAllProducts
      parameters:
        - name: name
          in: query
          description: Filter by product name (partial match)
          schema:
            type: string
        - name: minPrice
          in: query
          description: Filter by minimum price
          schema:
            type: number
            format: bigdecimal
        - name: maxPrice
          in: query
          description: Filter by maximum price
          schema:
            type: number
            format: bigdecimal
        - name: inStock
          in: query
          description: Filter only products in stock
          schema:
            type: boolean
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sort by field (e.g., price,asc or name,desc)'
          schema:
            type: string
            default: id,asc
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPageResponse'

    post:
      tags:
        - Products
      summary: Create a new product (ADMIN only)
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{productId}:
    get:
      tags:
        - Products
      summary: Get product by ID (public)
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Products
      summary: Update product (ADMIN only)
      operationId: updateProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Products
      summary: Delete product (ADMIN only)
      operationId: deleteProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Product deleted successfully
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ==================== ORDERS ====================
  /orders:
    get:
      tags:
        - Orders
      summary: Get orders (user's own or all for ADMIN)
      operationId: getAllOrders
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderPageResponse'

    post:
      tags:
        - Orders
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid input data or insufficient stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

# ==================== COMPONENTS ====================
components:
  schemas:
    # User Schemas
    UserRegistrationRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: John Doe
        email:
          type: string
          format: email
          maxLength: 255
          example: john.doe@example.com
        password:
          type: string
          format: password
          minLength: 6
          maxLength: 100
          example: SecurePass123

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@example.com
        role:
          type: string
          enum: [USER, ADMIN]
          example: USER
        createdAt:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'

    UserPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 100
        totalPages:
          type: integer
          example: 5

    # Product Schemas
    ProductCreateRequest:
      type: object
      required:
        - name
        - description
        - price
        - stockQuantity
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: Laptop Dell XPS 15
        description:
          type: string
          minLength: 1
          maxLength: 2000
          example: High-performance laptop with Intel i7 processor
        price:
          type: number
          format: bigdecimal
          minimum: 0.01
          example: 1299.99
        stockQuantity:
          type: integer
          minimum: 0
          example: 50

    ProductUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: Laptop Dell XPS 15
        description:
          type: string
          minLength: 1
          maxLength: 2000
          example: High-performance laptop with Intel i7 processor
        price:
          type: number
          format: bigdecimal
          minimum: 0.01
          example: 1299.99
        stockQuantity:
          type: integer
          minimum: 0
          example: 45

    ProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: Laptop Dell XPS 15
        description:
          type: string
          example: High-performance laptop with Intel i7 processor
        price:
          type: number
          format: bigdecimal
          example: 1299.99
        stockQuantity:
          type: integer
          example: 50
        createdAt:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'

    ProductPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 150
        totalPages:
          type: integer
          example: 8

    # Order Schemas
    OrderCreateRequest:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemRequest'

    OrderItemRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        quantity:
          type: integer
          minimum: 1
          example: 2

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 987e6543-e21b-12d3-a456-426614174999
        userId:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        status:
          type: string
          enum: [PENDING, PROCESSING, COMPLETED, CANCELLED]
          example: PENDING
        totalAmount:
          type: number
          format: bigdecimal
          example: 2599.98
        createdAt:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'

    OrderItemResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 456e7890-e12b-34d5-a678-901234567890
        productId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        productName:
          type: string
          example: Laptop Dell XPS 15
        quantity:
          type: integer
          example: 2
        priceAtOrder:
          type: number
          format: bigdecimal
          example: 1299.99
        subtotal:
          type: number
          format: bigdecimal
          example: 2599.98

    OrderPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 50
        totalPages:
          type: integer
          example: 3

    # Error Schema
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: Validation failed for object
        path:
          type: string
          example: /api/v1/products
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: price
              message:
                type: string
                example: must be greater than 0